apiVersion: v1
kind: Service
metadata:
  name: secure-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::118550600167:server-certificate/TestCert
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        # image:  <insert your own ECR repo/image here!> 
        image: 118550600167.dkr.ecr.us-east-2.amazonaws.com/bar:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000

